[tool.poetry]
name = "aws-data-pipeline"
version = "0.1.0"
description = ""
authors = ["Shubham <hireshubham.9360@gmail.com>"]
packages = [{ include = "etl" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
boto3 = ">=1.43.72"
pandas = ">=1.5.0,<2.1.0"
python-dotenv = ">=1.2.2"
pyarrow = ">=25.0.1"
numpy = ">=1.24,<2.0"

[tool.poetry.dev-dependencies]
pytest = ">=9.1.1"
moto = ">=5.2.2"
pytest-cov = ">=4.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"